import React, { useState } from "react";
import { fmt, fmtTs, isoToRu, TENDER_STATUS } from "../shared";
import EntityThread from "./EntityThread";
import { Field } from "../modals";
import { supabase } from "../supabaseClient";
export const TENDER_PAYMENT_KINDS = { customer_payment: "Оплата от заказчика", supplier_payment: "Оплата поставщику", partner_dumping_in: "Партнёр передал демпинговое обеспечение", partner_dumping_out: "Вернули партнёру демпинговое обеспечение", partner_bank_in: "Партнёр передал банковское обеспечение", partner_bank_out: "Вернули партнёру банковское обеспечение" };
export function tenderPartnerBalance(payments, tenderId, type) {
  return payments.filter((p) => p.tender_id === tenderId && p.kind.startsWith(`partner_${type}_`)).reduce((sum, p) => sum + (p.kind.endsWith("_in") ? 1 : -1) * Number(p.amount), 0);
}
export function TenderRegister({ tenders, partners, people, selectedId, onSelect }) {
  const [query, setQuery] = useState(""); const [state, setState] = useState("");
  return <section className="wf-workspace"><div className="wf-filters"><label>Поиск тендера<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Номер, заказчик, предмет" /></label><label>Статус<select value={state} onChange={(e) => setState(e.target.value)}><option value="">Все</option>{Object.entries(TENDER_STATUS).map(([key, s]) => <option key={key} value={key}>{s.label}</option>)}</select></label></div><div className="wf-table-wrap"><table className="wf-table"><thead><tr><th>Тендер</th><th>Заказчик</th><th>Партнёр</th><th>Ответственные</th><th>Сумма</th><th>Период</th><th>Статус</th></tr></thead><tbody>{tenders.filter((t) => (!state || t.status === state) && `${t.contract_no} ${t.title} ${t.customer}`.toLowerCase().includes(query.toLowerCase())).map((t) => <tr key={t.id}><td><button className="wf-task-title" aria-expanded={selectedId === t.id} onClick={() => onSelect(selectedId === t.id ? null : t.id)}>{t.contract_no ? `№ ${t.contract_no}` : t.title || "Тендер"}</button><small>Создан {fmtTs(t.created_at) || "дата не сохранена"}</small></td><td>{t.customer}</td><td>{partners.find((p) => p.id === t.partner_id)?.name || "—"}</td><td>{(t.responsible_ids || []).map((id) => people.find((p) => p.id === id)?.full_name || "Сотрудник").join(", ") || "Не назначены"}</td><td>{fmt(t.amount)} ₸</td><td>{isoToRu(t.start_date)} — {isoToRu(t.end_date)}</td><td>{TENDER_STATUS[t.status]?.label || t.status}</td></tr>)}</tbody></table></div></section>;
}
export function PartnerTenderLinks({ partnerId, tenders, payments, onOpen }) {
  const rows = tenders.filter((t) => t.partner_id === partnerId);
  if (!rows.length) return <p className="kd-muted">Привязанных тендерных проектов нет.</p>;
  return <section className="wf-section"><h4>Тендерные проекты · {rows.length}</h4>{rows.map((t) => <div className="wf-file" key={t.id}><span><strong>{t.contract_no || t.title}</strong><small>{TENDER_STATUS[t.status]?.label || t.status} · {t.customer}</small><small>Вернуть партнёру: демпинг {fmt(tenderPartnerBalance(payments, t.id, "dumping"))} ₸ · банковское {fmt(tenderPartnerBalance(payments, t.id, "bank"))} ₸</small></span><button className="kd-btn ghost sm" onClick={() => onOpen(t)}>Открыть проект</button></div>)}</section>;
}
export function TenderCollaboration({ tender, people, payments, moves, guarantees, services = [], canEdit, canManageMoney, onReload }) {
  const [kind, setKind] = useState("customer_payment"); const [move, setMove] = useState(""); const [guarantee, setGuarantee] = useState(""); const [note, setNote] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const rows = payments.filter((p) => p.tender_id === tender.id);
  const incoming = kind.endsWith("_in") || kind === "customer_payment";
  const eligible = moves.filter((m) => m.direction === (incoming ? "income" : "expense") && !payments.some((p) => p.move_id === m.id));
  async function link() {
    if (!move || !note.trim() || (kind.startsWith("partner_") && !guarantee)) { setError("Выберите движение, обеспечение (для расчётов с партнёром) и основание."); return; }
    setBusy(true); setError("");
    try { const r = await supabase.rpc("link_tender_payment", { p_tender_id: tender.id, p_move_id: move, p_kind: kind, p_guarantee_id: kind.startsWith("partner_") ? guarantee : null, p_note: note.trim() }); if (r.error) throw r.error; await onReload(); setMove(""); setNote(""); }
    catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  return <div><section className="wf-section"><h4>Участники и контакты</h4><p>Создан {fmtTs(tender.created_at) || "дата не сохранена"} · {people.find((p) => p.id === tender.created_by)?.full_name || "Автор не сохранён"}</p><p>Ответственные: {(tender.responsible_ids || []).map((id) => people.find((p) => p.id === id)?.full_name || "Сотрудник").join(", ") || "Не назначены"}</p>{(tender.customer_contacts || []).map((c, index) => <p key={index}><strong>{c.name}</strong> · {c.role} · <a href={`tel:${c.phone}`}>{c.phone}</a> · {c.note}</p>)}</section>
    <section className="wf-section"><h4>Выплаты и расчёты с партнёром</h4><p className="kd-muted">Связи с проведёнными движениями по счетам. При привязке деньги повторно не списываются.</p><div className="wf-table-wrap"><table className="wf-table"><thead><tr><th>Дата</th><th>Операция</th><th>Сумма</th><th>Основание</th></tr></thead><tbody>{rows.map((p) => <tr key={p.id}><td>{isoToRu(p.paid_on)}</td><td>{TENDER_PAYMENT_KINDS[p.kind]}</td><td>{fmt(p.amount)} ₸</td><td>{p.note}</td></tr>)}</tbody></table>{!rows.length && <p className="wf-empty">Выплаты ещё не привязаны.</p>}</div><p>Осталось вернуть партнёру: демпинговое {fmt(tenderPartnerBalance(payments, tender.id, "dumping"))} ₸ · банковское {fmt(tenderPartnerBalance(payments, tender.id, "bank"))} ₸.</p>
    {canManageMoney && <details><summary>Привязать проведённую выплату</summary>{error && <p className="kd-err" role="alert">{error}</p>}<Field label="Назначение"><select value={kind} onChange={(e) => { setKind(e.target.value); setMove(""); }}>{Object.entries(TENDER_PAYMENT_KINDS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field>{kind.startsWith("partner_") && <Field label="Обеспечение тендера"><select value={guarantee} onChange={(e) => setGuarantee(e.target.value)}><option value="">Выберите</option>{guarantees.map((g) => <option key={g.id} value={g.id}>{g.kind} · {fmt(g.amount)} ₸</option>)}</select></Field>}<Field label="Движение по счёту"><select value={move} onChange={(e) => setMove(e.target.value)}><option value="">Выберите проведённое движение</option>{eligible.map((m) => <option key={m.id} value={m.id}>{isoToRu(m.move_date)} · {fmt(m.amount)} ₸ · {m.note}</option>)}</select></Field><Field label="Основание"><input value={note} onChange={(e) => setNote(e.target.value)} /></Field><button className="kd-btn primary sm" disabled={busy} onClick={link}>Привязать</button></details>}
    </section><EntityThread refreshKey={JSON.stringify([tender, rows, guarantees, services])} kind="tender" entityId={tender.id} people={people} canComment={canEdit} />
  </div>;
}
